kind: Sensor
apiVersion: kai.v1
metadata:
  id: net.dns_test
  name: "DNS Resolution Test"
  description: "Tests DNS resolution for common domains"
  tags: ["network", "dns"]
spec:
  backend: system
  type: cli
  command: 
    - "bash"
    - "-c"
    - |
      echo "=== DNS Resolution Test ==="
      for domain in google.com github.com api.anthropic.com; do
        if timeout 2 nslookup $domain >/dev/null 2>&1; then
          echo "✅ $domain: SUCCESS"
        else
          echo "❌ $domain: FAILED (timeout/no nameserver)"
        fi
      done
      echo ""
      echo "DNS Configuration:"
      cat /etc/resolv.conf 2>/dev/null || echo "Cannot read /etc/resolv.conf"
  timeoutSeconds: 10
  output:
    format: text
  safety:
    mode: read_only
    risk: low
