kind: Flow
apiVersion: kai.v1
metadata:
  id: flow.security_forensics
  name: "Security Incident Forensics"
  description: "Comprehensive security investigation using Tetragon eBPF"
  tags: ["security", "forensics", "tetragon"]
spec:
  steps:
    - id: get_tetragon_events
      type: sensor
      ref: tetragon.syscall_history
      with:
        lookback: "1h"
      output:
        saveAs: security_events

    - id: get_network_connections
      type: sensor
      ref: net.tcp_stats
      output:
        saveAs: network_data

    - id: analyze_breach
      type: agent
      agentType: analysis
      input:
        - fromStep: security_events
        - fromStep: network_data
      output:
        saveAs: breach_analysis

    - id: alert_security_team
      type: action
      ref: slack.notify
      condition: "{{ breach_analysis.confidence > 0.85 }}"
      with:
        channel: "#security-alerts"
        message: "🚨 Potential breach detected: {{ breach_analysis.root_cause }}"
