kind: Flow
apiVersion: kai.v1
metadata:
  id: flow.noisy_neighbor_suppressor
  name: "Kubernetes Noisy Neighbor Suppressor"
  description: "Detects and throttles pods causing performance interference"
  tags: ["kubernetes", "performance"]
spec:
  triggers:
    - type: metric_threshold
      metric: pod_cpu_throttling_rate
      condition: "value > 0.5"
      window: "30s"
  steps:
    - id: check_cgroup_throttling
      type: sensor
      ref: k8s.cgroup_throttling
      output:
        saveAs: throttling_data
    - id: identify_culprit
      type: agent
      agentType: analysis
      input:
        - fromStep: throttling_data
      output:
        saveAs: culprit_pod
    - id: throttle_pod
      type: action
      ref: k8s.throttle_pod
      condition: "{{ culprit_pod.confidence > 0.8 }}"
      with:
        namespace: "{{ culprit_pod.namespace }}"
        pod: "{{ culprit_pod.pod_name }}"
        cpu_limit: "500m"
