kind: Sensor
apiVersion: kai.v1
metadata:
  id: ebpf.exec_tracer
  name: eBPF Process Execution Tracer
  description: Traces execve() calls using eBPF
  tags: ["ebpf", "process", "security"]
spec:
  backend: system
  type: cli
  command: ["timeout", "{{duration}}", "sudo", "execsnoop-bpfcc"]
  params:
    duration:
      type: int
      default: 10
      description: How long to trace (seconds)
  output:
    format: text
  safety:
    mode: read_only
    risk: low
    requires_root: true
