kind: Sensor
apiVersion: kai.v1
metadata:
  id: net.tcp_retrans
  name: "TCP retransmit counter"
  description: "Counts TCP retransmissions using netstat"
spec:
  backend: system
  type: cli
  command: ["netstat", "-s"]
  timeoutSeconds: 5
  output:
    format: raw_text
  safety:
    mode: read_only
    risk: low
