kind: Sensor
apiVersion: kai.v1
metadata:
  id: ebpf.tcp_tracer
  name: "eBPF TCP Connection Tracer (CO-RE)"
  description: "Traces tcp_v4_connect using a CO-RE BPF program"
  tags: ["ebpf", "network", "core"]
spec:
  backend: ebpf
  type: ebpf
  with:
    bytecode: "recipes/sensors/ebpf/tcp_tracer/tcp_tracer.o"
    section: "tcp_v4_connect"
    attach_type: "kprobe"
    symbol: "__inet_stream_connect"
    ringbuf: "events"
  params:
    duration:
      type: int
      default: 10
      description: "Collection duration in seconds"
  output:
    format: event_stream
    schema:
      ts_ns: uint64
      pid: uint32
      saddr: ipv4
      daddr: ipv4
      sport: uint16
      dport: uint16
      family: uint8
      comm: string
  safety:
    mode: read_only
    risk: medium
