kind: Sensor
apiVersion: kai.v1
metadata:
  id: ebpf.dns_tracer
  name: "DNS Tracer"
  description: "Captures outbound DNS queries via custom eBPF program"
  tags: ["network", "dns", "ebpf"]
spec:
  backend: ebpf
  type: ebpf
  with:
    bytecode: "recipes/sensors/ebpf/dns_tracer/dns_tracer.o"
    section: "kprobe/udp_sendmsg"
    attach_type: "kprobe"
    symbol: "udp_sendmsg"
  params:
    duration:
      type: int
      default: 10
      description: "Collection duration in seconds"
  output:
    format: event_stream
  safety:
    mode: read_only
    risk: medium
