kind: Sensor
apiVersion: kai.v1
metadata:
  id: ebpf.file_tracer
  name: eBPF File Access Tracer
  description: Traces file open() calls using eBPF
  tags: ["ebpf", "security", "files"]
spec:
  backend: system
  type: cli
  command: ["timeout", "{{duration}}", "sudo", "opensnoop-bpfcc"]
  params:
    duration:
      type: int
      default: 10
      description: How long to trace (seconds)
  output:
    format: text
  safety:
    mode: read_only
    risk: low
    requires_root: true
