kind: Flow
apiVersion: kai.v1
metadata:
  id: flow.pod_crashloop_investigator
  name: "Pod CrashLoop Investigator"
  description: "Investigates why pods are crashing repeatedly"
  tags: ["kubernetes", "crash"]
spec:
  triggers:
    - type: k8s_event
      event_type: pod_crashloop
  steps:
    - id: get_pod_logs
      type: sensor
      ref: k8s.pod_logs
      with:
        namespace: "{{ trigger.namespace }}"
        pod: "{{ trigger.pod }}"
        tail: 100
      output:
        saveAs: pod_logs
    - id: get_pod_events
      type: sensor
      ref: k8s.pod_events
      with:
        namespace: "{{ trigger.namespace }}"
        pod: "{{ trigger.pod }}"
      output:
        saveAs: pod_events
    - id: diagnose
      type: agent
      agentType: analysis
      input:
        - fromStep: pod_logs
        - fromStep: pod_events
      output:
        saveAs: crash_diagnosis
    - id: maybe_rollback
      type: action
      ref: k8s.rollback_deployment
      condition: "{{ crash_diagnosis.recommended_action == 'rollback' }}"
      with:
        namespace: "{{ trigger.namespace }}"
        deployment: "{{ crash_diagnosis.deployment }}"
