kind: Flow
apiVersion: kai.v1
metadata:
  id: flow.network_latency_rootcause
  name: "Network Latency Root Cause"
  description: "Diagnoses packet loss, congestion, and routing issues"
  tags: ["network", "latency", "performance"]
spec:
  triggers:
    - type: metric_threshold
      metric: http_request_duration_p99
      condition: "value > 0.2"
      window: "10s"
  steps:
    - id: check_tcp_stats
      type: sensor
      ref: net.tcp_stats
      output:
        saveAs: tcp_data
    - id: check_packet_drops
      type: sensor
      ref: net.packet_drops
      output:
        saveAs: packet_data
    - id: check_conntrack
      type: sensor
      ref: net.conntrack_usage
      output:
        saveAs: conntrack_data
    - id: correlate
      type: agent
      agentType: correlation
      input:
        - fromStep: tcp_data
        - fromStep: packet_data
        - fromStep: conntrack_data
      output:
        saveAs: network_diagnosis
    - id: maybe_flush_conntrack
      type: action
      ref: net.flush_conntrack
      condition: "{{ network_diagnosis.recommended_action == 'flush_conntrack' }}"
