kind: Action
apiVersion: kai.v1
metadata:
  id: system.log_alert
  name: "Log alert"
  description: "Writes an alert to the local log sink"
  tags: ["system", "alert"]
spec:
  backend: system
  operation: log_alert
  params:
    severity:
      type: string
      default: info
    message:
      type: string
      required: true
  safety:
    mode: write
    risk: low
    requiresApproval: false
