kind: Sensor
apiVersion: kai.v1
metadata:
  id: system.sleep
  name: "Sleep / wait"
  description: "Waits for a specified duration"
  tags: ["utility"]
spec:
  backend: system
  type: cli
  command: ["sleep", "{{duration}}"]
  timeoutSeconds: 120
  params:
    duration:
      type: int
      default: 10
      required: true
  output:
    format: raw_text
  safety:
    mode: read_only
    risk: low
