kind: Flow
apiVersion: kai.v1
metadata:
  id: flow.tls_cert_monitor
  name: "TLS Certificate Monitor"
  description: "Monitors TLS certificate expiration and misconfigurations"
  tags: ["tls", "security"]
spec:
  triggers:
    - type: schedule
      cron: "0 0 * * *"
  steps:
    - id: check_certs
      type: sensor
      ref: tls.cert_check
      with:
        endpoints:
          - "api.example.com:443"
          - "internal-service:8443"
      output:
        saveAs: cert_data
    - id: analyze_expiry
      type: agent
      agentType: analysis
      input:
        - fromStep: cert_data
      output:
        saveAs: cert_analysis
    - id: alert_expiring
      type: action
      ref: slack.notify
      condition: "{{ cert_analysis.days_until_expiry < 30 }}"
      with:
        channel: "#security"
        message: "TLS cert expiring soon: {{ cert_analysis.affected_component }}"
