kind: Flow
apiVersion: kai.v1
metadata:
  id: flow.cloud_cost_optimizer
  name: "Cloud Cost Optimization Agent"
  description: "Identifies idle resources and recommends cost savings"
  tags: ["cloud", "cost", "optimization"]
spec:
  triggers:
    - type: schedule
      cron: "0 */6 * * *"
  steps:
    - id: scan_idle_nodes
      type: sensor
      ref: cloud.idle_nodes
      with:
        idle_threshold: 0.1
        duration: 1200
      output:
        saveAs: idle_nodes
    - id: calculate_savings
      type: agent
      agentType: analysis
      input:
        - fromStep: idle_nodes
      output:
        saveAs: cost_analysis
    - id: downsize_nodes
      type: action
      ref: cloud.downsize_nodes
      condition: "{{ cost_analysis.savings_usd > 100 }}"
      with:
        node_ids: "{{ cost_analysis.node_list }}"
        reason: "Automated by Kai"
