kind: Sensor
apiVersion: kai.v1
metadata:
  id: tls.cert_check
  name: "TLS certificate checker"
  description: "Validates TLS certificates for a list of endpoints"
  tags: ["tls", "security"]
spec:
  backend: tls
  type: api
  operation: cert_check
  params:
    endpoints:
      type: list
      required: true
  output:
    format: structured
  safety:
    mode: read_only
    risk: low
