kind: Flow
apiVersion: kai.v1
metadata:
  id: flow.live_network_tracer
  name: Live Network Activity Monitor (eBPF)
  description: >
    Real-time analysis of TCP connection behavior using native CO-RE eBPF tracing.
    Combines kernel-level telemetry with system TCP statistics and generates an
    AI-assisted performance and anomaly diagnosis.
  tags: ["ebpf", "network", "demo"]
spec:
  steps:
    - id: trace_tcp_connections
      type: sensor
      ref: ebpf.tcp_tracer
      with:
        duration: 10
      capture: events
      output:
        saveAs: tcp_trace

    - id: get_network_stats
      type: sensor
      ref: net.tcp_stats
      output:
        saveAs: tcp_stats

    - id: analyze_patterns
      type: agent
      agentType: analysis
      input:
        - name: tcp_events
          fromStep: tcp_trace
        - name: tcp_stats
          fromStep: tcp_stats
      prompt: |
        You are an expert Linux kernel and networking performance engineer.
        Analyze the following data:

        1. Real-time TCP connection events from eBPF (connect attempts):
           {{ tcp_trace.events | tojson }}

        2. System TCP statistics (netstat -s):
           {{ tcp_stats.stdout }}

        Your goals:
        - Detect abnormal TCP behavior (high failure rate, unusual ports, bursts).
        - Identify slow servers, repeated timeouts, SYN retransmissions, misconfigs.
        - Determine root cause categories:
          * Application issue
          * Kernel network stack
          * Firewall / packet filter
          * DNS trouble
          * Latency / congestion
          * Misconfigured service
        - Suggest the next recommended action.

        Provide output as:
        {
          "root_cause": "...",
          "affected_component": "...",
          "recommended_action": "...",
          "confidence": number (0-1),
          "reasoning": "short justification"
        }
      output:
        saveAs: network_analysis

    - id: report
      type: action
      ref: system.log_alert
      with:
        severity: info
        message: "{{ network_analysis.root_cause }}"
